/**
 * Zero-cost placeholder provider for media capabilities (image/video/speech/thumbnail) that no
 * free/local model can realistically produce yet. It returns a structured placeholder descriptor
 * instead of a real asset, so the full pipeline can be exercised end-to-end (including QA and
 * export) without any API key, and so swapping in a real media provider (FLUX, Veo, HyperFrames,
 * ElevenLabs — see docs/architecture/AI_INFRASTRUCTURE.md) later requires zero changes to any
 * Agent or Engine, only registering a new provider with a higher-priority tier.
 */

import { defineProvider } from './providerInterface.js';

const CAPABILITIES = ['generate_image', 'generate_video', 'generate_speech', 'generate_thumbnail'];

export function createMockMediaProvider({ id = 'mock-local-media' } = {}) {
  return defineProvider({
    id,
    capabilities: CAPABILITIES,
    tier: 'local',
    estimateCostUsd: () => 0,
    estimateDurationMs: () => 10,
    async execute(request) {
      return { output: placeholderFor(request), costUsd: 0 };
    },
  });
}

function placeholderFor(request) {
  const { capability, input } = request;
  const description = input.prompt || input.description || JSON.stringify(input);
  return {
    placeholder: true,
    mediaType: capability.replace('generate_', ''),
    description,
    note: 'Generated by the local placeholder media provider. Register a real image/video/voice provider to produce actual media.',
  };
}
