/**
 * A deterministic, zero-cost, zero-dependency text provider. This is the "local model" tier of
 * the cost waterfall (Cache -> Local -> Browser -> Free -> Low-cost -> Premium) — it never calls
 * the network, so it is always available, always free, and safe to run in tests/CI/examples
 * without any API key. Real deployments register it alongside paid providers so the Provider
 * Router only reaches for a paid tier when the mock provider genuinely can't do the job (i.e.
 * never, for text) or when a real provider is explicitly preferred/required for quality.
 */

import { defineProvider } from './providerInterface.js';

const CAPABILITIES = ['generate_text', 'summarize', 'translate', 'reason', 'analyze', 'create_storyboard'];

export function createMockTextProvider({ id = 'mock-local-text' } = {}) {
  return defineProvider({
    id,
    capabilities: CAPABILITIES,
    tier: 'local',
    estimateCostUsd: () => 0,
    estimateDurationMs: () => 5,
    async execute(request) {
      return { output: runMockCapability(request), costUsd: 0 };
    },
  });
}

function runMockCapability(request) {
  const { capability, input } = request;
  switch (capability) {
    case 'generate_text':
      return generateText(input);
    case 'summarize':
      return summarize(input.text || '');
    case 'translate':
      return `[${input.targetLanguage || 'en'}] ${input.text || ''}`;
    case 'reason':
    case 'analyze':
      return `Based on "${truncate(input.question || input.context || '', 80)}", the key consideration is: ${truncate(input.context || input.question || 'no additional context was provided', 120)}.`;
    case 'create_storyboard':
      return buildStoryboard(input.script || input.text || '');
    default:
      throw new Error(`mock provider does not implement capability "${capability}"`);
  }
}

function generateText(input) {
  const prompt = input.prompt || input.goal || '';
  const tone = input.tone ? ` in a ${input.tone} tone` : '';
  const audience = input.audience ? ` for ${input.audience}` : '';
  const body = truncate(prompt, 240);
  return `${capitalize(body)}${audience}${tone}. Generated by the local-tier mock provider — swap in a real ` +
    `provider (see packages/providers) for production-quality output.`;
}

function summarize(text) {
  const sentences = text.split(/(?<=[.!?])\s+/).filter(Boolean);
  return sentences.slice(0, 2).join(' ') || text;
}

function buildStoryboard(script) {
  const beats = script.split(/\n+/).filter(Boolean);
  const scenes = (beats.length ? beats : [script]).map((beat, i) => ({
    scene: i + 1,
    description: truncate(beat, 100),
  }));
  return { scenes };
}

function truncate(text, max) {
  if (text.length <= max) return text;
  return `${text.slice(0, max - 1)}…`;
}

function capitalize(text) {
  return text ? text[0].toUpperCase() + text.slice(1) : text;
}
